[package]
name = "my-dapp"
version = "1.0.0"
authors = []

[addresses]
net2dev_addr = "a29b957ed111749a3ad41f30c208661a1a592e5e1f9831757a04783eb7054d87"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "aptos-release-v1.25"
subdir = "aptos-framework"

[dev-dependencies]
